name: Clean Workflow Logs

on:
  workflow_dispatch:
    inputs:
      days_old:
        description: "The amount of days old to delete"
        default: "7"
        required: false

jobs:
  clean-logs:
    runs-on: ubuntu-latest
    steps:
       - name: Remove artifacts
        # You may pin to the exact commit or the version.
        # uses: c-hive/gha-remove-artifacts@24dc23384a1fa6a058b79c73727ae0cb2200ca4c
        uses: c-hive/gha-remove-artifacts@v1.2.0
        with:
          # Artifacts older than this will be deleted (e.g. "2 months", "1 day"). Parsed by moment.
          age: ${{ github.events.input.days_old }}
          # Access token for the repository, available under the same name in secrets.
          GITHUB_TOKEN: ${{ github.token }}
          # true/false. If enabled, tag build artifacts (e.g. release artifacts) will be kept.
          skip-tags: false
          # Keep the specified number of artifacts even if they are older than the age.
          skip-recent: 1